version: '3'
services:
    pihole:
        restart: unless-stopped
        container_name: pihole
        image: pihole/pihole:2025.03.0
        environment:
            FTLCONF_dns_reply_host_IPv4: "${PIHOLE_SERVERIP:-127.0.0.1}"
            VIRTUAL_HOST: pi.hole
            VIRTUAL_HOST_NAME: "pihole"
            FTLCONF_dns_listeningMode: 'all'
        expose:
            - "53"
            - "67"
            - "80"
            - "443"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        volumes:
            - "./pihole/resolv.conf:/etc/resolv.conf:ro"
            - "pihole_datadir:/etc/pihole"
volumes:
    pihole_datadir:
